### PR TITLE
Customise date time format

### PR DESCRIPTION
**Pull request by Silver343**
This PR allows users to customise their date time format, I have provided 6 options, if the number of options were to be expanded then the method of selection would need to change.

I have applied the users date format to all filament `datetime()` methods.

I have not applied it to the dates using Iso format.

There is already a fallback format applied via the .env file or tables config file.

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Sorry, I just merged and did a few fixes, can you resolve the merge conflicts?

**Comment by Silver343** [comment]
No problem, I'll take a look.

**Comment by Cannonb4ll** [comment]
@Silver343 So where does the date time format change once I change it in my profile? I just updated it in my profile, but when viewing an item, the format isn't changing.

**Comment by Silver343** [comment]
The format will change anywhere filament is being used to format it, this is mainly the resource pages and my page, in the other date times are formatted via carbons iso format, which can be customised but it is done via locale.

So I guess to do all date times would require to settings, one for locale and one for format of the filament dates.

**Comment by Cannonb4ll** [comment]
I'm not sure how much of this would apply properly for the front end having this setting there then. Users that don't have admin access, will get confused about this setting as it doesn't change anything for them.

**Comment by Cannonb4ll** [comment]
@Silver343 What do you think?

**Comment by Silver343** [comment]
@Cannonb4ll I think you're right.

If the dates could be set similar to carbons iso format you could use a locale selector

**Comment by Cannonb4ll** [comment]
For now I'm closing this, if you feel this needs to be opened again let me know.

**Pull request closed without merging**
