### PR TITLE
Added more tweaks to SSO

### PR DESCRIPTION
**Pull request by aneeskhan47**
More configuration options.

### CODE REVIEW

**Comment by aneeskhan47** [comment]
@Cannonb4ll What do you think about this pr?

**Comment by aneeskhan47** [comment]
@ndijkstra

**Comment by Cannonb4ll** [comment]
Thanks, I'll test this next week!

**Comment by Cannonb4ll** [comment]
I just tested it, and as of now, this PR will break existing installations. I had a working SSO locally, after this PR it broke.

It's giving me this exception (while I had a working installation):

CleanShot 2022-08-17 at 10 06 55

And upon expecting, I think the matching data is wrong because I have everything in a `data` wrapper (which most have):

`if ($user === null || !Arr::has($user, explode(',', $providerUserEndpointKeys))) {`

CleanShot 2022-08-17 at 10 06 07
`dd()` ^ of $user and $providerUserEndpointKeys

**Comment by aneeskhan47** [comment]
@Cannonb4ll did you add `SSO_PROVIDER_USER_ENDPOINT_DATA_WRAP_KEY=data` in your env?

**Comment by Cannonb4ll** [comment]
> @Cannonb4ll did you add `SSO_PROVIDER_USER_ENDPOINT_DATA_WRAP_KEY=data` in your env?

No, I didn't. But that's kinda the point - it has to be backward compatible with installations that are already running and using this. If I merge this and release it, existing installations will break.

**Comment by aneeskhan47** [comment]
> > @Cannonb4ll did you add `SSO_PROVIDER_USER_ENDPOINT_DATA_WRAP_KEY=data` in your env?
> 
> No, I didn't. But that's kinda the point - it has to be backward compatible with installations that are already running and using this. If I merge this and release it, existing installations will break.

Ok I think I fixed it. now $providerUserEndpointDataWrapKey defaults to 'data'.

**Comment by aneeskhan47** [comment]
> > > @Cannonb4ll did you add `SSO_PROVIDER_USER_ENDPOINT_DATA_WRAP_KEY=data` in your env?
> > 
> > 
> > No, I didn't. But that's kinda the point - it has to be backward compatible with installations that are already running and using this. If I merge this and release it, existing installations will break.
> 
> Ok I think I fixed it. now $providerUserEndpointDataWrapKey defaults to 'data'.

Can you check now please?

**Comment by aneeskhan47** [comment]
@Cannonb4ll I have added that you can also have wrap key like 'data.user' if its nested. cause as you may know `Arr:get` supports dot notation. and I have set the wrap key defaults to `data`. you may check now 😄 . and sorry for any inconvenience ❤️

**Comment by Cannonb4ll** [comment]
No problem, all good now!

**Pull request merged**
