### PR TITLE
Select custom project icons

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
It works with blade icons :-)

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
CleanShot 2022-07-10 at 15 14 40@2x

It also works in combination with the private option

**Comment by Cannonb4ll** [comment]
Can you check the merge conflicts?

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll here you go! 🙏

**Review by ndijkstra — APPROVED** [review]

**Comment by ndijkstra** [comment]
Maybe add some tests?

**Comment by Cannonb4ll** [comment]
> > Maybe add some tests?
> 
> Anything else?😜

@SebastiaanKloos Hamburger pls. 🍔

**Pull request merged**
