### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by yordadev**
## What?
This Pull Request adds docker support to Roadmap for self contained local development as requested in https://github.com/ploi-deploy/roadmap/issues/60

## Getting up and running..
Go into docker folder and run:
`docker-compose up -d --build`

Running artisan commands:
`docker exec -it roadmap php artisan <command>`

Will be running on `localhost:1337` and PhpMyAdmin is running on `localhost:8010` 

## Considerations?

There are a few heroicons that were giving issues when running locally with docker.

```
Unable to locate a class or view for component <insert heroicon name here>
```
The problem was resolved by simply changing the following icons:

x-heroicon-o-chevron-down -> x-heroicon-s-chevron-down (group.blade.php)
heroicon-o-chat -> heroicon-s-chat (CommentResource)
heroicon-o-archive -> heroicon-s-archive (ItemResource)
heroicon-o-x-circle -> heroicon-o-collection (notifications.blade.php)

Related Issues:

https://github.com/laravel-filament/filament/issues/2677
https://github.com/blade-ui-kit/blade-heroicons/issues/9

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Nice @yordadev, loving this! I will test this asap. Could you also add installation instructions to the readme below the SSO login part on how to set this up? ❤️

**Comment by Taronyuu** [comment]
@yordadev Is there any specific reason you decided to go with a manual Dockerfile and not include Laravel Sail?

**Comment by yordadev** [comment]
> @yordadev Is there any specific reason you decided to go with a manual Dockerfile and not include Laravel Sail?

No reason in particular other than being old fashioned. 👍🏼 👴🏼

**Comment by yordadev** [comment]
> Nice @yordadev, loving this! I will test this asap. Could you also add installation instructions to the readme below the SSO login part on how to set this up? ❤️

@Cannonb4ll Will do. 🥇 💪🏼

**Comment by yordadev** [comment]
> Nice @yordadev, loving this! I will test this asap. Could you also add installation instructions to the readme below the SSO login part on how to set this up? ❤️

Added, let me know if needs adjustment.

**Comment by Cannonb4ll** [comment]
Seems good to me!

**Pull request merged**
