### PR TITLE
Ability to add tags for item

### LINKED ISSUE #99: Tags
Ability to add tags to items

### PR DESCRIPTION
**Pull request by krekas**
Closes #99 

Frontend:
image

Backend:
image

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
Seems to work great, small design flaw, it seems there's a line here even though there's no tags attached:

CleanShot 2022-10-04 at 08 42 22@2x

**Comment by Cannonb4ll** [comment]
Also, it would be great if admins could manage the already created tags (and once you delete them, they detach from the already created items).

**Comment by krekas** [comment]
@Cannonb4ll everything done I think

**Comment by Cannonb4ll** [comment]
Thanks! 🤝

**Pull request merged**
