### PR TITLE
Notify subscribers setting

### LINKED ISSUE #75: Ability to not send any notifications for admins when changing project/board
CleanShot 2022-06-16 at 09 18 24

As of now, if you change any value for the project or board above, any users that are subscribed to this item will receive a notification. There should be a checkbox that says "Disable notifications" (which doesn't save, but it will disable the notifications when you update it)

Use case would be for example if you want to silently close an item, or move an item without notifying users because it would be unrelated/unneeded.

### PR DESCRIPTION
**Pull request by ndijkstra**
Closes #75

### CODE REVIEW

**Comment by Cannonb4ll** [comment]
What's up with that failing test? Should be unrelated right?

**Comment by ndijkstra** [comment]
mmm, weird. It's not failing when I run it locally

**Comment by Cannonb4ll** [comment]
I think you overdid this feature 😊

What I meant was, when editing, have a checkbox that allows you to disable notifications for that update you're doing, that's why I described it as it doesn't save:

> As of now, if you change any value for the project or board above, any users that are subscribed to this item will receive a notification. There should be a checkbox that says "Disable notifications" (which doesn't save, but it will disable the notifications when you update it)

**Comment by ndijkstra** [comment]
How would you do it without saving? Will sessions work for this since the observer will notify the subscribers.

This PR will temporary save the setting and then the observer will reset it

**Comment by Cannonb4ll** [comment]
You're right, I was too fast with reviewing ,awesome!

**Pull request merged**
